blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: [GITHUB_REPO_URL]/discussions
    about: Please ask and answer questions here.
  - name: Security Vulnerabilities
    url: [GITHUB_REPO_URL]/security/policy
    about: Please report security vulnerabilities here.
